### ISSUE TITLE
A test to know if there is a difference

### ISSUE THREAD

**Issue by aborruso** [paulfitz/daff#101]
Hi,
is there a way in daff to have "true" if there is a diff between two input files?

I'm using `daff one.csv two.csv | wc -l`. If it's > 1 there is a diff. Is it right?

Thank you

**Comment by paulfitz** [comment]
Merged a `--fail-if-diff` flag, see `daff help`.  Feel free to reopen if it doesn't work for you.  Cheers!

**Comment by aborruso** [comment]
@paulfitz first of all thank you

I have updated daff with `pip install daff --upgrade`. When I run `daff help` I have

```
Traceback (most recent call last):
  File "/usr/local/bin/daff", line 11, in <module>
    load_entry_point('daff==1.3.27', 'console_scripts', 'daff')()
  File "/usr/local/bin/daff.py", line 11699, in main
    Coopy.main()
  File "/usr/local/bin/daff.py", line 3565, in main
    ret = coopy.coopyhx(io)
  File "/usr/local/bin/daff.py", line 3451, in coopyhx
    return self.run(args,io)
  File "/usr/local/bin/daff.py", line 3438, in run
    raise _HxException(e1)
daff._HxException: TypeError('coercing to Unicode: need string or buffer, NoneType found',)
```

I have python 2.7.

When I run `daff fileA.csv fileB.csv` (there is no diff between them) I have the same result of `daff --fail-if-diff fileA.csv fileB.csv`.

What's my error?

**Comment by paulfitz** [comment]
Hmm I'll check the help problem, d'oh :-).

If it is working, then `daff --fail-if-diff fileA.csv fileB.csv` should return a status of 1 if fileA.csv and fileB.csv are different (like the `cmp` command).  So `daff --fail-if-diff fileA.csv fileB.csv && echo same || echo different` should print same for files that are the same and different for files that are different.  If different, it will also show the diff, you can redirect that to `/dev/null` if you don't want it.

**Comment by aborruso** [comment]
@paulfitz it works, thank you

Proabably I prefef (because I'm not so good bash user) a more boolean result. Now I have something like

```
@@,field1,field2,...
same
```

With my `daff one.csv two.csv | wc -l.` I have something that I'm able to use immediately (because I'm very dummy).

**Comment by dogmatic69** [comment]
```
if daff --fail-if-diff fileA.csv fileB.csv; then
   echo "No diff"
else
   echo "There is a diff"
fi
```
You can also do it inline

```
diff --fail-if-diff fileA.csv fileB.csv && echo "No diff" || echo "There is a diff"
```

**Comment by aborruso** [comment]
@dogmatic69 you are very kind.

Thank you again to you and @paulfitz
