### ISSUE TITLE
daff with Python

### ISSUE THREAD

**Issue by bstiel** [paulfitz/daff#108]
I've been following the Python example and tried the following:

```
import daff
import colorama
colorama.init()

data1 = []
data2 = [['5', '5', '9'], [None, None, None], ['2', '6', '9'], ['1', '1', '9']]

flags = daff.CompareFlags()

table_diff = daff.diff(data1, data2)
renderer = daff.TerminalDiffRender(flags)
s = renderer.render(table_diff)
print(s)
```

And the output is

```
!  ,+++
@@ ,9
+++,null
+++,9
+++,9
```

i.e. it only shows the last column in the diff. 

How can I make it showing the full row (couldn't find anything in the docs)?

Thank you!

**Comment by paulfitz** [comment]
daff treats the first row as a header row, like in the CSV format.  Add a header with distinct column names and things should work better:

```
data1 = [['a', 'b', 'c']]
data2 = [['a', 'b', 'c'], ['5', '5', '9'], [None, None, None], ['2', '6', '9'], ['1', '1', '9']]
```

**Comment by bstiel** [comment]
excellent, that's exactly what I was looking for.
Thanks so much for your help (and your excellent package)!
