### ISSUE TITLE
Get html output in Python

### ISSUE THREAD

**Issue by stellarhoof** [paulfitz/daff#111]
I can't, for the life of me, get styled HTML output in Python. https://github.com/paulfitz/daff/issues/108 was my starting point, but even following http://paulfitz.github.io/daff-doc/ I'm lost. I've got two lists of lists. Like:

```
data1 = [['header1', 'header2'], [3, 4], [5, 6]]
data2 = [['header1', 'header2'], [1, 2], [3, 4]]
```

With
```
  flags = daff.CompareFlags()
  flags.ids = ['sourceID']
  flags.columns_to_ignore = args.ignore_columns
  print(daff.diffAsAnsi(data1, data2, flags))
```

I get output, but with `daff.diffAsHtml` I get nothing :(

**Comment by paulfitz** [comment]
Eek this looks like a bug to me. Working on a fix in #112.  I see you closed this, perhaps you found a work-around - if you still need one let me know.
