### ISSUE TITLE
daff.Coopy.diffAsHtml does not producethe same output as --output-format html --fragment

### ISSUE THREAD

**Issue by Godsmith** [paulfitz/daff#136]
On http://paulfitz.github.io/daff-doc/types/coopy/Coopy.html, it says

> diffAsHtml (local : Table, remote : Table, ?flags : CompareFlags) : String
> Compare two tables and visualize their difference using html
> Parameters:
> 
> local the reference version of the table
> remote another version of the table
> flags control how the comparison will be made
> **Returns: an html string like that produced by daff --output-format html --fragment a.csv b.csv**

However, this is not true in my testing:

```
12:44 $ cat csv1.csv
1,2,3
a,b,c

12:45 $ cat csv2.csv
1,2,3
a,b,d

12:43 $ cat test.py
import daff 

with open('csv1.csv') as f1:
    with open('csv2.csv') as f2:
        data1 = f1.read()
        data2 = f2.read()

        table1 = daff.PythonTableView(data1)
        table2 = daff.PythonTableView(data2)

        flags = daff.CompareFlags()
        print(daff.Coopy.diffAsHtml(table1, table2, flags))
	
10:23 $ daff --output-format html --fragment csv1.csv csv2.csv
<table>
<thead>
<tr class="header"><th>@@</th><th>1</th><th>2</th><th>3</th></tr>
</thead>
<tbody>
<tr class="modify"><td class="modify">→</td><td>a</td><td>b</td><td class="modify">c→d</td></tr>
</tbody>
</table>

12:43 $ python3 test.py
<table>
<thead>
<tr class="header"><th>@@</th><th>1</th></tr>
</thead>
<tbody>
<tr class="gap"><td>...</td><td>...</td></tr>
<tr><td></td><td>,</td></tr>
<tr class="add"><td>+++</td><td>d</td></tr>
<tr class="remove"><td>---</td><td>c</td></tr>
<tr><td></td><td>
</td></tr>
</tbody>
</table>
```

As you can see, running the python script does not say that only a cell differs, but rather says that the entire row has been replaced.

The example code at https://pypi.org/project/daff/ has a similar effect, so I'm struggling with how to produce the output produced by --output-format html using the Python classes.

Perhaps the example on https://pypi.org/project/daff/ could be updated so that it produces similar code to --output-format html?

**Comment by paulfitz** [comment]
Try `table1 = daff.Csv().makeTable(data1)` instead.

There is a type problem. `data1` in your example will be the string `"1,2,3\na,b,c"` but `PythonTableView` expects it to be in the form of a table like `[[1,2,3],['a','b','c']]`.  By feeding in a string, I think daff is seeing your tables as a single column, with each character on a separate row.  The `daff.Csv` class can help you parse CSV if you want, or there's the native `csv` python module.

**Comment by Godsmith** [comment]
Right, that was a stupid mistake on my part. Closing this. Thank you for your support!
