### ISSUE TITLE
Excel to json format diff

### ISSUE THREAD

**Issue by koenvb** [paulfitz/daff#142]
I would like to use daff to compare excell workbooks. 
I was playing around this weekend and it gives me very good results if I export the sheets to CSV and then compare them but its a bit cumbersome to create the csvs for each sheet and then compare them. 

Then looking into docs I saw you can compare json files as well. Would there be a way to convert an excell workbook into the json format you propose in the docs? Would there be a conversion tool to convert excell to json and then run it through daff to see the changes? 

Thanks a lot for this beautiful library! It made me look at Haxe as well :-)

**Comment by paulfitz** [comment]
Hi @koenvb, one option could be to install `gnumeric` and use its `ssconvert` utility to convert from excel workbooks to csv files, and then compare the csv using `daff`.  There are lots of other conversion tools and libraries though.  Gnumeric also has a `ssdiff` utility which can be handy in some cases for comparing workbooks.
