### ISSUE TITLE
Segfaults when using option --id

### ISSUE THREAD

**Issue by turion** [paulfitz/daff#150]
I have two time series `csv`s where the first value is the UNIX timestamp.

```
bin/Coopy-debug --id unix_time --color a.csv a.csv 
Segmentation fault (Speicherabzug geschrieben)
```

When I call the same without the `--id` option, it works as expected.

**Comment by paulfitz** [comment]
Thanks for reporting.  Is it possible to share the csvs?

**Comment by turion** [comment]
Sorry, I cannot reproduce currently, as I'm trying to use the Python version again. If I encounter the bug again, I'll reopen and create an example CSV.
