### ISSUE TITLE
Chrome ext  wy-z/github-csv-diff  is in Chrome web store. Floppy's is not.

### ISSUE THREAD

**Issue by porteusconf** [paulfitz/daff#152]
Floppy's  chrome extension, which is no longer in the store, is mentioned on bottom-most line at [https://paulfitz.github.io/daff/](https://paulfitz.github.io/daff/)  which says:
> You can get the same results online on github using <a href="http://floppy.org.uk/">Floppy</a>'s <a href="https://github.com/theodi/csvhub">csvhub</a> chrome extension. </p> 
``` html
<p class="explain">
--
  | You can get the same results online on github using <a href="http://floppy.org.uk/">Floppy</a>'s <a href="https://github.com/theodi/csvhub">csvhub</a> chrome extension.
  | </p>
``` 

But Floppy's chrome extension from 2015 is *not* in store anymore. However, a similar extension is available: [wy-z/github-csv-diff](https://github.com/wy-z/github-csv-diff)  So perhaps fix by:
``` html
<p class="explain">
--
  | You can get the same results online on github using <a href="https://chrome.google.com/webstore/detail/github-csv-diff/ngpdjmibpbemokfbmapemhpbmgacebhg/">Github CSV Diff chrome extension by WeiYang </a> at  <a href="https://github.com/wy-z/github-csv-diff">/wy-z/github-csv-diff</a> 
  | </p>
```
That is 

> You can get the same results online on github using <a href="https://chrome.google.com/webstore/detail/github-csv-diff/ngpdjmibpbemokfbmapemhpbmgacebhg/">Github CSV Diff chrome extension by WeiYang </a> at  <a href="https://github.com/wy-z/github-csv-diff">/wy-z/github-csv-diff</a>

**Comment by paulfitz** [comment]
Hey thanks!  I've updated the webpage.
