### ISSUE TITLE
Publish a new package to npm

### ISSUE THREAD

**Issue by MPeli** [paulfitz/daff#175]
Hi,

   I noticed that fibers were updated to version 5 (d0c5237ed9d8a42b06d71037b862447360082823) but a new package has not been released. @paulfitz, could you release it please?

Thank you, Martin.

**Comment by paulfitz** [comment]
Done now I think. Let me know if there's a problem. I feel guilty for the fibers dependency, there isn't much need for it, I should remove it.

**Comment by MPeli** [comment]
Thank you, the update of fibers helped, I managed to install it. I am trying to [import ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) into an angular project. Unfortunately, it seems that the daff.js is not a [js module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). Would it be possible to update it? Thank you.

**Comment by MPeli** [comment]
I found some Haxe modules which might be helpful.
- https://github.com/benmerckx/genes (Generates split ES6 modules and Typescript definitions from Haxe modules.)
- https://github.com/elsassph/hxtsdgen (This is a TypeScript declaration file generator for the Haxe JavaScript output target.)

**Comment by MPeli** [comment]
I also noticed that `node_modules/daff/bin/daff.js` contains a comment `#!/usr/bin/env node` on the first line.

I managed to make the `daff` work.
1. Remove the comment
2. Add `daff.js` into `angular.json`
```
"scripts": [
  "node_modules/daff/bin/daff.js"
]
```  
3. Add `declare var daff: any;` into your component

Would it be possible for you to remove the [hashtag comment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#hashbang_comments) please?
