### ISSUE TITLE
Version published to bower is very old (1.3.16)

### ISSUE THREAD

**Issue by edg2s** [paulfitz/daff#179]

**Comment by paulfitz** [comment]
I think bower has been deprecated for some time?

I went ahead and updated https://github.com/paulfitz/daff-web which is the source of the bower package, let me know if there are any problems.

**Comment by edg2s** [comment]
> I think bower has been deprecated for some time?

I'm going off the readme which recommends using bower. If there's a better way then the readme should be updated?
