### ISSUE TITLE
daff.Table in javascript

### ISSUE THREAD

**Issue by karissa** [paulfitz/daff#18]
Hey

I am trying to use daff.Ndjson, but it requires a Table instance to start with.

```js
    var data1 = new daff.Table()
    var data2 = new daff.Table()
    var table1 = new daff.Ndjson(data1)
    var table2 = new daff.Ndjson(data2)
```

Gives me an error -- Table isn't defined. I've tried to use TableView and SimpleView, but I get 
```js
TypeError: Object #<Object> has no method 'get_width'
```

Thanks

**Comment by paulfitz** [comment]
You should be on the right track with TableView. Does something like this work for you?
```js
var data1 = new daff.TableView([["name","thinginess"],["space",5],["earth",20]]);
var table1 = new daff.Ndjson(data1);
table1.renderRow(1); // should give '{"name":"space","thinginess":5}'
table1.render(); // should give full table as ndjson
```

`daff.Table` itself is just an interface that can't be instantiated. Things that implement that interface in javascript are TableView and SimpleTable (SimpleView is something else - very sorry for the confusing naming).

**Comment by karissa** [comment]
That's great but I actually wanted to read in ndjson into a table. Is that
possible?

**Comment by paulfitz** [comment]
If you have the ndjson as one big string (e.g. coming from a file) then you can use `Ndjson.parse` (or `Ndjson.addRow` if you have per-row strings). For example:

```js
var target = [];  // where you want to read to
var loader = new daff.Ndjson(new daff.SimpleView(target));
var loader.parse('{"name":"space","thinginess":5}\n{"name":"earth","thinginess":20}\n');
// target should now be [[ 'name', 'thinginess' ],[ 'space', 5 ],[ 'earth', 20 ]]
```
Ndjson's methods are listed here: http://paulfitz.github.io/daff-doc/types/coopy/Ndjson.html. This is a corner of daff I haven't spent much time on yet, if there's something in particular you have in mind for it just let me know.

**Comment by paulfitz** [comment]
@karissa I realized I'm assuming you're talking about ndjson as a file format, but maybe you mean a table expressed in json as something like:
```js
[
  { "key1": "val1a", "key2": "val2a" },
  { "key1": "val1b", "key2": "val2b" },
  ...
]
```
If so, I have an adaptor for that which I could clean up and add, if it were useful. Basically an alternative implementation of the `daff.Table` interface that assumes a list-of-hashes rather than a list-of-lists.

**Comment by karissa** [comment]
Hey!

Thanks for the responses. Yeah, I just hadn't tried SimpleView! I was using SimpleTable. OK, thanks.

I wasn't particularly interested in the json table format.

This is what I'm building: https://github.com/maxogden/dat-core/issues/2

Essentially we will have a db.compare method that will output ndjson of changes like so: https://github.com/karissa/dat-visualdiff/blob/master/test.js#L10
(but as ndjson, not a json array table)

If we'd have any feature request, it'd be some sort of adapter for this kind of value stream of changes.

**Comment by paulfitz** [comment]
Nifty, I think I see. What you have in TEST_DATA/STREAM looks like it could map well onto an intermediate stage daff has, which could let you reuse the diff visualization part. I'll poke at the plumbing.

**Comment by karissa** [comment]
@paulfitz yeah! exactly. that'd be great. I'd open a PR to Haxe myself (looked at the code for about an hour yesterday) but figured I'd drop you a line.

**Comment by karissa** [comment]
Maybe a cool thing to add would be an ndjson stream parser for `daff.SimpleView`?

How does Haxe handle streams?

**Comment by karissa** [comment]
The link to the doc is broken :( http://preview.lib.haxe.org/p/nodehx/0.10.26/files/nodejs/stream/Readable.hx

**Comment by karissa** [comment]
@paulfitz  this doesn't work:

```
var target = [];  // where you want to read to
var loader = new daff.Ndjson(new daff.SimpleView(target));
var loader.parse('{"name":"space","thinginess":5}\n{"name":"earth","thinginess":20}\n');
// target should now be [[ 'name', 'thinginess' ],[ 'space', 5 ],[ 'earth', 20 ]]
```

Error:
```
> var loader = new daff.Ndjson(new daff.SimpleView(target));
TypeError: Object  has no method 'getCellView'
    at Object.coopy.Ndjson.$hx_exports.coopy.Ndjson [as __class__] (/Users/karissa/dev/node_modules/daff-ndjsonstream/node_modules/daff/lib/daff.js:3071:18)
    at repl:1:14
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
```

**Comment by paulfitz** [comment]
I had some typos, a stray `var` and wrote `SimpleView` instead of `TableView`:
```js
var target = [];  // where you want to read to
var loader = new daff.Ndjson(new daff.TableView(target));
loader.parse('{"name":"space","thinginess":5}\n{"name":"earth","thinginess":20}\n');
// target should now be [[ 'name', 'thinginess' ],[ 'space', 5 ],[ 'earth', 20 ]]
```
This time I pasted straight from the terminal so should really work :-)

**Comment by karissa** [comment]
yay thanks @paulfitz

**Comment by paulfitz** [comment]
Also, since I haven't found time yet to come up with a cleaner solution, I went ahead and committed an adaptor that might be useful, see https://github.com/paulfitz/daff/blob/master/test/test_native_ndjson.js and https://github.com/paulfitz/daff/blob/master/env/js/ndjson_table_view.js

**Comment by karissa** [comment]
You rock, thanks! i'll let you know if we end up using it. Building some more low level pieces at the moment but we plan on it!

**Comment by paulfitz** [comment]
For haxe+streams, an alternative to that broken link you found is this: http://haxefoundation.github.io/hxnodejs/js/node/stream/Readable.html - it is just declaring node's classes for use within haxe, not doing anything new.

I'm interested in how you'll make diffs and streams work (regardless of whether you use daff or not). I can imagine streams of differences, but can't quite wrap my head around differences of streams, if that makes any sense. Big fan of all things dat, good luck with the visual differ!

**Comment by karissa** [comment]
Ah thanks for the link! Google's search shows the broken one. Looks straightforward.

I think we are going to batch views every 50 or so rows. Here's a module we're using https://github.com/maxogden/sorted-diff-stream, and here's the current state of the simple diffing mechanism for dat: https://github.com/maxogden/dat/blob/beta/bin/diff.js

Thanks for putting in some work on this, really happy that you responded. If there's anything else that seems fishy or if I hit my head against the proverbial wall again, I'll let you know! Woo daff!

**Comment by karissa** [comment]
Can you republish on npm to get this in there? :)

**Comment by paulfitz** [comment]
oops, should be there now
