### ISSUE TITLE
Configure `git show` to work as `git diff` does

### ISSUE THREAD

**Issue by sjackman** [paulfitz/daff#19]
`git diff HEAD~1..HEAD` works as expected, but `git show` shows a standard line-by-line diff. Can `daff git tsv` configure `git show` to use daff?

**Comment by paulfitz** [comment]
Hmm, looks like you can do `git show --ext-diff`, does that work for you? Not sure how to set that to be the default.

**Comment by sjackman** [comment]
Yeah, that works for me. Thanks.

**.gitconfig**
```
[alias]
	show-tsv = show --ext-diff
```
