### ISSUE TITLE
Configure `git diff` to use a different format when piped into a pager

### ISSUE THREAD

**Issue by sjackman** [paulfitz/daff#20]
I often use MacVim as my pager like so `git diff |gview -`. The ANSI escape colour codes don't display well in Vim. My current configuration (through zsh prezto), `git diff` displays pretty colours by default, and no colours when piped into a pager like `git diff | less`. Can daff be configured like that?

**Comment by paulfitz** [comment]
I tried doing this for myself a while back but ran into a git issue that had me stymied. Took another shot and I think I have it working now. Can you see if daff v1.2.9 (npm/js version) does what you want? You'll need to remove any `--color` flag that `daff git tsv` added to your `.gitconfig` file or daff will continue to always use ANSI color.

**Comment by sjackman** [comment]
Works great! Thanks.
