### ISSUE TITLE
Shortcut command to combine daff, daff render and open

### ISSUE THREAD

**Issue by sjackman** [paulfitz/daff#21]
Thanks for daff! It's fantastic. I use the following alias often. Could it be a standard command? It would helpful for `daff render` to accept two arguments and diff those tables.

```sh
# Daff a TSV/CSV file and open it in a browser
daff-render()
{
	daff $1 $2 >! $1-$2
	daff render --output $1-$2.html $1-$2
	open $1-$2.html
}
```

**Comment by paulfitz** [comment]
Glad daff is useful to you! We could certainly collapse the first two steps into a single command. Would something like this be adequate?
```
daff --output foo.html a.tsv b.tsv
```
So, when diffing, if you specify a .html output, the render step gets folded in?

The call to open the browser would need some OS-specific logic to call start/open/xdg-open. How important do you see it to fold that step in as well?

**Comment by sjackman** [comment]
Your recommendation looks great. The `open` step can be left out. Though, `daff --open a.tsv b.tsv` would be pretty cool. `--open` could accept the name of a program, like `--open=firefox` that defaults to say `$BROWSER` or falls back to `open`.

**Comment by paulfitz** [comment]
Ok, I implemented the `daff --output foo.html a.tsv b.tsv` part, will look at adding something `--open`-like when I get a chance. Do you have a thought on where the temporary file that'd be passed to the browser should go?

**Comment by sjackman** [comment]
Use [mktemp](http://unixhelp.ed.ac.uk/CGI/man-cgi?mktemp).

**Comment by sjackman** [comment]
And thanks!

**Comment by paulfitz** [comment]
What should we do about cleaning up the temporary file? daff may finish before the browser is done loading the file, unless we do hacky stuff. Might be simplest to just document that `--open` generates a file on each call, and then give a cleanup command that gets rid of them in bulk if the user actually cares. I guess we'd put them in a certain directory so that we can find them again to delete them. Does that sound plausible or am I overcomplicating this?

**Comment by sjackman** [comment]
Good point. One hacky option, but would probably work in practice, is to create the temp file in `/tmp`, open the web browser, and fork a background process to sleep for five or ten seconds to give the browser time to start, and then delete the temp file. A other option would be to create a file named by `--output` if its specified, and have `--output` default to `$1-$2.daff.html` in the current working directory, i.e. `a.tsv.b.tsv.daff.html`.

**Comment by paulfitz** [comment]
I finally took a shot at this. As of version `1.2.19` daff has a `--www` option that sends output to a browser. It uses a minimal web server to avoid an intermediate temporary file. Just tested on linux so far.

**Comment by sjackman** [comment]
Great! I tested it on a Mac, and it opens a new tab in my browser, Google Chrome, but the page is blank and the URL is `about:blank`.
```
❯❯❯ daff --www a.tsv b.tsv
```

**Comment by paulfitz** [comment]
Hmm, did some testing on a Mac, saw a slightly different issue and fixed that. Not confident that it'll fix what you are seeing, but can you try again just to see?

**Comment by sjackman** [comment]
It works! Beauty. Thanks, Paul.
