### ISSUE TITLE
Option to not prune unchanged columns

### ISSUE THREAD

**Issue by leonth** [paulfitz/daff#23]
`--all` prevents pruning on unchanged rows, however it stills prune unchanged columns. Can we have an option to not prune unchanged columns?

**Comment by paulfitz** [comment]
Good point, I just made `--all` prevent pruning entirely, and added `--all-rows` and `--all-columns` for anyone who wants finer control. Should be fixed in npm package version 1.2.12. Please let me know if there are any problems. Thanks!

**Comment by leonth** [comment]
That was fast... the new `--all` behaviour worked very well for me. Thanks!
