### ISSUE TITLE
bug when everything is an added column?

### ISSUE THREAD

**Issue by karissa** [paulfitz/daff#25]
I've been able to produce this bug, where the column names are repeated twice when everything in the table is an added column. Can you reproduce it?

![screen shot 2015-04-21 at 11 49 31 am](https://cloud.githubusercontent.com/assets/633012/7260100/94928fb8-e81c-11e4-9cc3-7ede140251d2.png)

**Comment by paulfitz** [comment]
Are you seeing that when going from an empty table to a table with stuff in it? If so - I have not been sure what to do with that case. In some sense the header row does indeed get inserted, and the patch logic is simpler with the diff as shown. But the diff does look goofy. I'll fix this.

**Comment by karissa** [comment]
Yeah, that's the case I'm working with. It's because I'm creating a module that does streaming diffs, i.e., paging through the table, and all of the rows in that page happen to be new. I think this is a rare case but I've just been testing
