### ISSUE TITLE
Noisy diffs

### ISSUE THREAD

**Issue by tsibley** [paulfitz/daff#27]
First off, awesome looking tool!  I'm very excited that I stumbled upon daff and coopy today.

I wanted to report that it seems like daff can generate pretty noisy diffs where shared lines are not detected as shared and thus contribute to larger diff hunks.

Consider the two example files, a and b, in [this gist](https://gist.github.com/tsibley/688b6859e48cfc21e0ad).

`git diff --no-index --color a b` produces a sensibly simple diff of mostly lines added, with a few cell values changed in a handful of lines.

`daff diff --color a b` produces much more churn in the diff hunks, presumably because of some threshold for shared lines.

Is this a tunable behaviour in any way?

**Comment by paulfitz** [comment]
`daff` currently has a tough time with repeated rows, its algorithm does best when it can cobble together some kind of approximate primary key for the table. That said, it should have been able to do better than this. I've added a commit that fixes an asymmetry in a relevant heuristic (`daff diff b a` was not bad) and gives a better result for your case.

For tuning, the main control doesn't apply in your case - if you happen to know which set of columns are a good choice as a primary key, you can tell daff that with `--id col1 --id col2 --id col3`. But your case doesn't really have a key.

You can shorten the diff a bit with `--context 0` just to show only rows with changes.

**Comment by tsibley** [comment]
Thanks!  That change seems to work pretty well.  I'm looking forward to using daff more!
