### ISSUE TITLE
Daff python version does not create a daff executable.

### ISSUE THREAD

**Issue by akshetpandey** [paulfitz/daff#28]
Running `pip install daff` creates a daff.py executable but not a daff executable. Missing the daff executable breaks the scripts.

**Comment by paulfitz** [comment]
Just so I understand, you are saying an executable called `daff.py` is insufficient, it should be named `daff`?

**Comment by akshetpandey** [comment]
Yes, `daff.py git csv` doesn't work as it expect the name of the executable to be `daff`

**Comment by paulfitz** [comment]
Ah, ok, I'll check that. That command is supposed to have logic to check for `daff`, `daff.py`, or `daff.rb`. If that logic is fixed, would it be okay to continue calling the executable `daff.py`? The daff packages in different languages would clash otherwise. I'm not sure if that would be a problem but I'm not anxious to find out :-)

**Comment by paulfitz** [comment]
I fixed some issues with `daff.py git csv`, if you get a chance to try it out I'd be interested in hearing if the results are adequate.

**Comment by akshetpandey** [comment]
@paulfitz : Everything seems to be working fine now. No exceptions when using daff.py. Thanks for the quick fix.

**Comment by paulfitz** [comment]
Thanks for testing, @akshetpandey!

**Comment by akshetpandey** [comment]
@paulfitz : It seems that the latest version has ANSI coloring disabled?

**Comment by paulfitz** [comment]
@akshetpandey you're right, this was a regression. Fixed in f686b7bb1ab01612480473ada5c0c74448e7ed08, will do releases shortly.

**Comment by paulfitz** [comment]
@akshetpandey released a fix, let me know if the problem persists.

**Comment by akshetpandey** [comment]
The issue is fixed, sorry about the late update.
