### ISSUE TITLE
git diff driver with renamed files dies with “Expected 7 parameters from git, but got 9.”

### ISSUE THREAD

**Issue by tsibley** [paulfitz/daff#29]
```
trsibley@mullion-13 reports (master +=) $ GIT_TRACE=1 git diff --cached
09:18:20.051692 git.c:349               trace: built-in: git 'diff' '--cached'
09:18:20.054729 run-command.c:351       trace: run_command: '/usr/bin/less'
09:18:20.055439 run-command.c:199       trace: exec: '/usr/bin/less'
09:18:20.061627 run-command.c:351       trace: run_command: 'daff diff --color --git' 'reports/autopsy_quality.csv' '/var/folders/9_/78fx8kdx6zg3pkrr7pg3lb7r0000gq/T//8KWu29_autopsy_quality.csv' '76ad6f051d89f2fcfbd75395d
rename from reports/autopsy_quality.csv
rename to reports/autopsy_quality_dna.csv
index 76ad6f0..22ec65a 100644
'
09:18:20.062293 run-command.c:199       trace: exec: '/bin/sh' '-c' 'daff diff --color --git "$@"' 'daff diff --color --git' 'reports/autopsy_quality.csv' '/var/folders/9_/78fx8kdx6zg3pkrr7pg3lb7r0000gq/T//8KWu29_autopsy_
rename from reports/autopsy_quality.csv
rename to reports/autopsy_quality_dna.csv
index 76ad6f0..22ec65a 100644
'
Expected 7 parameters from git, but got 9
fatal: external diff died, stopping at reports/autopsy_quality.csv
trsibley@mullion-13 reports [128] (master +=) $
```

**Comment by tsibley** [comment]
It appears that this isn't due to `--cached`, but that the changed files in question were renamed.

**Comment by paulfitz** [comment]
Hey thanks for reporting this. Could you do me a favor and grab the full text output of the long lines in that trace? They are truncated currently. I'd like to see what the last two parameters are, to see if I can safely tell daff to ignore them.

**Comment by tsibley** [comment]
Ah, crap, sorry for missing that. I'll grab it.

**Comment by tsibley** [comment]
From a fresh minimal reproduction case.

```
trsibley@mullion-13 daff-issue-29 (master +) $ git log -p
commit cc4e803306f8cdb6ec37abf12757c190ced4dba1
Author: Thomas Sibley <tom@…>
Date:   Mon Jun 22 21:19:58 2015 -0700

    foo

diff --git a/foo b/foo
new file mode 100644
index 0000000..8819ccf
--- /dev/null
+++ b/foo
@@ -0,0 +1,2 @@
+foo,bar,baz
+baz,bat,bam
trsibley@mullion-13 daff-issue-29 (master +) $ git st
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    foo -> bar

trsibley@mullion-13 daff-issue-29 (master +) $ PAGER=cat GIT_TRACE=1 git diw
21:23:00.509392 git.c:555               trace: exec: 'git-diw'
21:23:00.509801 run-command.c:351       trace: run_command: 'git-diw'
21:23:00.511241 git.c:283               trace: alias expansion: diw => 'diff' '--cached'
21:23:00.511261 git.c:349               trace: built-in: git 'diff' '--cached'
21:23:00.512891 run-command.c:351       trace: run_command: 'daff diff --input-format csv --ordered --color --git' 'foo' '/var/folders/9_/78fx8kdx6zg3pkrr7pg3lb7r0000gq/T//3UX0vP_foo' '8819ccf3e92a65fcef8f968f15a75f8124674d43' '100644' 'bar' '8819ccf3e92a65fcef8f968f15a75f8124674d43' '100644' 'bar' 'similarity index 100%
rename from foo
rename to bar
'
21:23:00.513560 run-command.c:199       trace: exec: '/bin/sh' '-c' 'daff diff --input-format csv --ordered --color --git "$@"' 'daff diff --input-format csv --ordered --color --git' 'foo' '/var/folders/9_/78fx8kdx6zg3pkrr7pg3lb7r0000gq/T//3UX0vP_foo' '8819ccf3e92a65fcef8f968f15a75f8124674d43' '100644' 'bar' '8819ccf3e92a65fcef8f968f15a75f8124674d43' '100644' 'bar' 'similarity index 100%
rename from foo
rename to bar
'
Expected 7 parameters from git, but got 9
fatal: external diff died, stopping at foo
trsibley@mullion-13 daff-issue-29 [128] (master +) $ 
```

**Comment by paulfitz** [comment]
Thanks @tsibley. Do you have any git-related variables in your environment? I'm having trouble replicating this. It does look like the last two arguments you see could be safely ignored, but I'd like to nail down their origin.

**Comment by tsibley** [comment]
I didn't see any config or env vars which would affect this, so I went looking in git.  The [`run_external_diff()` function](https://git.kernel.org/cgit/git/git.git/tree/diff.c#n2960) adds the last two arguments when `other` is set.  `other` is set in the [`run_diff()` function (the caller of `run_external_diff()`)](https://git.kernel.org/cgit/git/git.git/tree/diff.c#n3155) when working on a renamed file.  The reason the penultimate argument is necessary (`other`) is to provide the new logical filename in case the blob was written to a temp file (like `foo` was in the above example).  This happens when the blobs being compared aren't the versions in the working tree.

**Comment by paulfitz** [comment]
Thanks for digging down @tsibley. I realize now I'm using an oldish git version (1.9.1), will try replicating in a recent version. What version are you at?

**Comment by tsibley** [comment]
2.2.2

**Comment by paulfitz** [comment]
Oh good catch. I can replicate now. #30 makes a tweak, see what you think. It just passes on git's opinion and diffs (in case file was changed a bit).

**Comment by tsibley** [comment]
Vanilla git-diff still includes the `---` and `+++` lines after the rename block (`git_args[8]`), so maybe daff should too?  The `+++ b/` line in that case should use `git_args[7]` instead of `path`.  (I'd offer a patch myself, but I'm not setup to hack on daff at the moment due to haxe version issues.)

An example from vanilla git-diff:

```
similarity index 50%
rename from foo
rename to bar
index 8819ccf..bc07ad2 100644
--- a/foo
+++ b/bar
[the diff]
```
