### ISSUE TITLE
Feature request: Ignore whitespace (-w) option

### ISSUE THREAD

**Issue by tsibley** [paulfitz/daff#36]
I don't know if this belongs in daff or coopy (and if in coopy, where), but it'd be great if `daff diff` supported an `--ignore-whitespace / -w` option which ignored whitespace changes when producing a diff.  Among other uses, this would help with auditing whitespace-only changes such as stripping leading/trailing spaces from field values.  I find GNU diff and git diff's ignore whitespace options to be invaluable!

**Comment by paulfitz** [comment]
sounds like a good idea - will look into it.
