### ISSUE TITLE
Issue while converting daff library to java

### ISSUE THREAD

**Issue by get2parag** [paulfitz/daff#39]
Hi,
I'm trying to use the daff library in a java project to do differences on certain objects and publish an htm report. For doing that i need to convert the current project into a java project / jar to be included as a library.
But the conversion of daff project from haxe to java isn't happening. Installed the haxe library on my windows systems as described here http://old.haxe.org/download and followed the instruction to making a java project from here : http://old.haxe.org/doc/start/java.
Getting the following error :- ./coopy/SqlHelper.hx:11: characters 4-92 : Class not found : Map
when I run this command :- >haxe -main coopy.Coopy -java <sys_path>\daff_java -cp src -D coopyhx_util.
Any idea what I could be doing wrong or something special needed to be done to use the library as a java project?

**Comment by paulfitz** [comment]
That sounds like an old version of haxe is creeping in there somehow. What does `haxe -version` give?

There's a prepackaged version of daff at https://github.com/paulfitz/daff/releases/tag/v1.2.1 - now I know there's at least one potential java user, I'll start making regular java releases.

**Comment by paulfitz** [comment]
There's an up to date java build at https://github.com/paulfitz/daff/releases/tag/v1.3.2 now. Let me know if you have any trouble with it.

**Comment by get2parag** [comment]
This one worked like a charm. All I had to do was include the lib in my java project. 
Once again thanks for taking time out and giving a java build.

One suggestion, you may put the latest build on a popular repo management tool like maven : http://search.maven.org/ . Here is the guide : https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by paulfitz** [comment]
Glad that worked for you @get2parag. Will poke at maven. Please do file any issues or inconviences you run into, you're the first known user of a java build.
