### ISSUE TITLE
Feature Request: Immutable Columns

### ISSUE THREAD

**Issue by foysavas** [paulfitz/daff#65]
Is there a way to specify that certain columns are immutable when comparing tables?

More concretely, this would result in a diff that deletes a row and then inserts a row, whenever a field seems to have been updated in a column specified as immutable.

I need this for a project of mine and don't mind coding it for everyone if it is missing.

**Comment by foysavas** [comment]
Specifying immutable columns as part of a composite PK during alignment gives me what I need.

Thanks for the great code!

**Comment by paulfitz** [comment]
Glad that you were able to do what you needed @foysavas.
