### ISSUE TITLE
Display of unicode rightwards arrow in Terminal

### ISSUE THREAD

**Issue by poliquin** [paulfitz/daff#69]
I am using `daff` with `git` to diff tab-delimited files. I get the following output when diff-ing a simple table (instead of seeing a rightwards arrow):

```diff
@@, hello,world
,   1,    2
+++,8,    9
---,3,    4
<E2><86><92>,  5<E2><86><92>0,  6
```

Note that I can run `echo -e "\xe2\x86\x92"` from my terminal and get the expected rightwards arrow.

Any ideas what might cause this?

Here are the lines from my `.gitconfig`:

```
[diff "daff-tab"]
	command = daff diff --input-format tsv --git
```

**Comment by paulfitz** [comment]
Hmm, not sure.  This might be a pager issue?  See e.g. http://stackoverflow.com/questions/17320721/git-diff-shows-unicode-symbols-in-angle-brackets

**Comment by paulfitz** [comment]
As a work-around, the latest version of daff has a `--plain` option that will use a plain `->` arrow rather than trying to be clever.

**Comment by poliquin** [comment]
Thanks. I'll look into it further if I have time and report back. The pager issue is a good lead.

**Comment by poliquin** [comment]
Yes, this is pager issue. I could not fully resolve the problem, but the following works fine:

    git --no-pager diff

So, this is not a problem with `daff`. Also, thank you for the new `--plain` option!
