### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by dplusic** [paulfitz/daff#75]
Currently in daff npm package (version 1.3.18):
```javascript
// node_modules/daff/lib/daff.js:8080
/* $hx_exports = */ typeof window != "undefined" ? window : exports

// fix_exports.js
if (typeof exports != "undefined") {
  // ...
} else {
  // ...
}
```
This code causes problem when there are both `window` and `exports`.
Coopy is exported to `window` by `$hx_exports`, but 'fix_exports.js' looks up coopy in `exports`.

With Haxe Compiler 3.3.0, However, coopy is exported to `exports` first.
```javascript
/* $hx_exports = */ typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this

// fix_exports.js
if (typeof exports != "undefined") {
  // ...
} else {
  // ...
}
```

It would be better to rebuild the package with new haxe compiler and publish again.

**Comment by paulfitz** [comment]
Ok, I used haxe 3.3.0 and bumped up the npm version, did that resolve your issue?  If not, would you be able to sketch a short test case to tickle this issue.

**Comment by dplusic** [comment]
Resolved, thank you!

Note:
This problem was caused by electron render process.
