### ISSUE TITLE
python package for 1.3.22 not working in python 3

### ISSUE THREAD

**Issue by semio** [paulfitz/daff#82]
Hi Paul,

when trying to import daff lib 1.3.22 into python, we got this error: 

```
In [1]: import daff
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-539af51566a0> in <module>()
----> 1 import daff

/Users/semio/.pyenv/versions/3.6.0/bin/daff.py in <module>()
     64 import functools as python_lib_Functools
     65 import json as python_lib_Json
---> 66 from itertools import imap
     67 from itertools import ifilter
     68 try:

ImportError: cannot import name 'imap'
```

where `imap` is python 2 only function. And lib for 1.3.19 is working on python 3. Please check if you can add back support for that. Let me know if you need more infomation/help form me :)

**Comment by paulfitz** [comment]
Oh thanks for reporting, I think I need to roll back the haze version I use.

**Comment by paulfitz** [comment]
@semio does 1.3.23 work for you?  Sorry for the glitch.

**Comment by semio** [comment]
thanks @paulfitz, works like a charm! We can close this issue now.
