### ISSUE TITLE
Stop after N diffs are found

### ISSUE THREAD

**Issue by mrbrahman** [paulfitz/daff#92]
Is there a parameter (or can one be added?) to abort after finding the first N diffs? This will be really helpful for tables with large diffs, and working on them a few at a time makes sense than seeing all the diffs at the same time.

Thanks!

**Comment by dogmatic69** [comment]
What if a record is moved from the top row to the bottom for example, that would require processing the entire diff. Can you not use a tool like less/more etc to limit what you are viewing of a diff (much like git does with large diffs)

**Comment by mrbrahman** [comment]
> What if a record is moved from the top row to the bottom for example

I'm not sure I understand this use case. Can you please elaborate?

**Comment by dogmatic69** [comment]
A diff needs to be done on the entire set for it to be accurate. 

Simplified, moved one record (A) to the bottom
```
A      B
B => B
B      A
```

If you view only 2/3's of the exact same diff, you would see:
```
A      B
B => B
```
Now it looks like A simply changed to B or A has been removed. 

Git uses a pager on large commits, which is what I was saying you should look into. less/more are the common ones built into *nix systems.

**Comment by mrbrahman** [comment]
Thanks!
