### ISSUE TITLE
Option to output only Diff columns

### ISSUE THREAD

**Issue by mrbrahman** [paulfitz/daff#93]
For tables that have many columns, the Coopy format (of a few columns before and after the actual diff column) is making the output very large, and sort of unusable. Is it possible to add a parameter to restrict the output only to the diff columns (in addition to may be the ID columns that identify the row / row number)?

Thanks!

**Comment by paulfitz** [comment]
The `CompareFlags.unchanged_column_context` flag gives control over this I believe.  If set to 0 no context columns are included.  I think a "..." will still be shown - could get rid of that if it is a problem.  Do you use daff as a cli program or as a library?  I see that as a cli this option isn't exposed yet, sorry about that.

**Comment by mrbrahman** [comment]
My end-use is actually for structured "big-data", specifically on Spark. So, I'll be mostly using it as a library.

With that background, let me also post the other questions I have:

1. Does Haxe also compile to Scala? I think I can use a Java jar for a Scala program, but it would be nice if native Scala is supported.
2. The `TableView` wrapper - does it involve making a copy of the data into the `Table` format, or is it just some kind of meta-data container? I'm hoping it is the latter :-)
3. Are there any major road blocks that you can see for `daff` to be used for scattered (though properly distributed and sorted) big-data?

Thanks!

**Comment by paulfitz** [comment]
1. I don't think haxe has a Scala back-end unfortunately.
2. No copies, just a wrapper.
3. How big is big?  For larger data, I use daff's sql support.  There are time consuming elements, such as checking each corresponding row to see if any column has changed, that would need to look at all your data.

**Comment by paulfitz** [comment]
#121 should help with this.
