### ISSUE TITLE
Update readme to reflect all current command line options

### ISSUE THREAD

**Issue by jheeffer** [paulfitz/daff#94]
Hi! It seems the readme is outdated compared to what is possible according to the cli help.

Compare

https://github.com/paulfitz/daff/blob/master/README.md#the-program

with

https://github.com/paulfitz/daff/blob/master/coopy/Coopy.hx#L895-L973

Took me a while to find the `--unordered` flag I used before : )

**Comment by paulfitz** [comment]
Done (very belatedly) - thanks :-)
